export const data = [
  {
    id: 1,
    title: 'Do the dishes',
    completed: false,
    isToday: true,
    hour: '10:00',
    date: '2021-05-20',
  },
  {
    id: 2,
    title: 'Do the laundry',
    completed: false,
    isToday: false,
    hour: '11:00',
    date: '2021-05-20',
  },
  {
    id: 3,
    title: 'Do the homework',
    completed: true,
    isToday: true,
    hour: '12:00',
    date: '2021-05-20',
  },
  {
    id: 4,
    title: 'Do the shopping',
    completed: false,
    isToday: false,
    hour: '13:00',
    date: '2021-05-20',
  },
  {
    id: 5,
    title: 'Do the laundry two',
    completed: false,
    isToday: false,
    hour: '11:00',
    date: '2021-05-20',
  },
  {
    id: 6,
    title: 'Do something else',
    completed: false,
    isToday: false,
    hour: '11:00',
    date: '2021-05-20',
  },
  {
    id: 7,
    title: 'Do something else more',
    completed: false,
    isToday: true,
    hour: '11:00',
    date: '2021-05-20',
  },
]
